// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHv9LZ3aRyzAVoS5p5WP28Ncpq2xtRw8s',
    appId: '1:35602861071:web:884ef048a5b778b6fbe77a',
    messagingSenderId: '35602861071',
    projectId: 'kaerikalo-mvp-backend',
    authDomain: 'kaerikalo-mvp-backend.firebaseapp.com',
    storageBucket: 'kaerikalo-mvp-backend.firebasestorage.app',
    measurementId: 'G-XEWCQRMLH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5rXNa3qWNg954_sz0ivlOSaVt2Orayk',
    appId: '1:35602861071:android:5dc5618c08ee6762fbe77a',
    messagingSenderId: '35602861071',
    projectId: 'kaerikalo-mvp-backend',
    storageBucket: 'kaerikalo-mvp-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQB05gAg7mIzEDvljrzflnN4yO-LSVps',
    appId: '1:35602861071:ios:d52ebaec19aaaa6afbe77a',
    messagingSenderId: '35602861071',
    projectId: 'kaerikalo-mvp-backend',
    storageBucket: 'kaerikalo-mvp-backend.firebasestorage.app',
    iosBundleId: 'com.example.kaerikaloMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQB05gAg7mIzEDvljrzflnN4yO-LSVps',
    appId: '1:35602861071:ios:d52ebaec19aaaa6afbe77a',
    messagingSenderId: '35602861071',
    projectId: 'kaerikalo-mvp-backend',
    storageBucket: 'kaerikalo-mvp-backend.firebasestorage.app',
    iosBundleId: 'com.example.kaerikaloMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHv9LZ3aRyzAVoS5p5WP28Ncpq2xtRw8s',
    appId: '1:35602861071:web:76a40f4e142c44dbfbe77a',
    messagingSenderId: '35602861071',
    projectId: 'kaerikalo-mvp-backend',
    authDomain: 'kaerikalo-mvp-backend.firebaseapp.com',
    storageBucket: 'kaerikalo-mvp-backend.firebasestorage.app',
    measurementId: 'G-98XB5H0SDE',
  );
}
